# Generated by Django 6.0.5 on 2026-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=5000000, verbose_name='اعتبار'),
        ),
    ]
